### ISSUE TITLE
Error Page shows no matter how ShowErrorPage value is set

### ISSUE THREAD

**Issue by rodneymcfarland** [ilich/MvcReportViewer#102] opened 2015-07-02 15:53 UTC
I am getting a Service unavailable error page with <add key="MvcReportViewer.ShowErrorPage" value="False"/> Help!

**Comment by mkamoski** [comment] 2015-07-02 23:33
Search my q and a here for a JavaScript Jacky way to show error details.

-|-

Mark Kamoski

781-552-0176

mkamoski@gmail.com

**Comment by Xifried** [comment] 2015-07-10 08:57
I have the same problem, so I:
- downloaded the source
- openend the project with VS2013
- Built all projects (which also triggered the download of the required nuget packages)
- Then I started the MvcReportViewerExample-project and get the following error: (Sorry its German)

[A]System.Web.WebPages.Razor.Configuration.HostSection kann nicht in [B]System.Web.WebPages.Razor.Configuration.HostSection umgewandelt werden. Der Typ "A" stammt von der "System.Web.WebPages.Razor, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" im Kontext "Default" am Speicherort "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Web.WebPages.Razor\v4.0_2.0.0.0__31bf3856ad364e35\System.Web.WebPages.Razor.dll".. Der Typ "B" stammt von der "System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" im Kontext "Default" am Speicherort "C:\Users\Bernhard\AppData\Local\Temp\Temporary ASP.NET Files\root\b908136f\7f058c0d\assembly\dl3\498272e6\6fc89b49_eebad001\System.Web.WebPages.Razor.dll"..

**Comment by ilich** [comment] 2015-07-13 21:27
Please set <add key="MvcReportViewer.ShowErrorPage" value="False" /> in the Web.config to see ASP.NET error page. I am not able to recreate the issues described above. Please let me know if you will find the cause of the problem and it has to be fixed in the helper library.

**Closed by ilich** 2015-07-13 21:27 UTC

**Comment by rodneymcfarland** [comment] 2015-07-13 21:38
Thanks for responding but I gave up and used the report viewer in webforms.
